name = "react-ppr-workers-app"
main = "./src/server/app.tsx"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat_v2"]

# experimental_assets = {directory = "public"}
legacy_assets = "./public"

[placement]
mode = "smart"

[build]
command = "npm run build:css && npm run build:js"

[[d1_databases]]
binding = "DB"
database_name = "pokemon"
database_id = "1bea6938-8777-4864-a72e-f5fa2179411f"

[define]
IS_PRERENDER = "false"
IS_CLIENT = "false"
