name = "react-ppr-workers"
main = "./src/server/eyeball.ts"
compatibility_date = "2024-09-09"

# experimental_assets = {directory = "public"}
legacy_assets = "./public"

[[services]]
service = "react-ppr-workers-app"
binding = "APP"
