name = "react-ppr-workers"
main = "./src/server/eyeball.ts"
compatibility_date = "2024-10-10"
compatibility_flags = ["nodejs_compat"]

# experimental_assets = {directory = "public"}
legacy_assets = "./public"

workers_dev = true

routes = [
  {pattern = "react-ppr-workers.sunilpai.dev", custom_domain = true }
]

[[services]]
service = "react-ppr-workers-app"
binding = "APP"
